[package]
name = "rel4_kernel"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustlib"
path = "src/lib.rs"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy_system_allocator = "0.6"
riscv = { git = "https://gitee.com/rcore-os/riscv", features = ["inline-asm"] }
log = "0.4"
spin = { version = "0.9", features = ["use_ticket_mutex"] }
sel4_common = { path = "./sel4_common" }
sel4_cspace = { path = "./sel4_cspace" }
sel4_vspace = { path = "./sel4_vspace"}
sel4_task = { path = "./sel4_task" }
sel4_ipc = { path = "./sel4_ipc" }
[features]
ENABLE_SMP = ["sel4_common/ENABLE_SMP", "sel4_task/ENABLE_SMP", "sel4_vspace/ENABLE_SMP"]

[profile.release]
lto = true
panic = "abort"  
 
[profile.dev]  
panic = "abort"